// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEUwK9JWZPUEfs46P4kB1zusvHx744OuM',
    appId: '1:723862345529:web:cdbb1b7d4cee6dab163ae8',
    messagingSenderId: '723862345529',
    projectId: 'placement-notifier-dcaaf',
    authDomain: 'placement-notifier-dcaaf.firebaseapp.com',
    storageBucket: 'placement-notifier-dcaaf.appspot.com',
    measurementId: 'G-37YDX9F1R2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTbB4RMJ7Gsz5M5APQs-N8B7VL_I7taNs',
    appId: '1:723862345529:android:68e160779a56b1db163ae8',
    messagingSenderId: '723862345529',
    projectId: 'placement-notifier-dcaaf',
    storageBucket: 'placement-notifier-dcaaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV8ryIVBcr1o4S3OZRPVBvrcKPzIibGiE',
    appId: '1:723862345529:ios:4c522d52f01b1d80163ae8',
    messagingSenderId: '723862345529',
    projectId: 'placement-notifier-dcaaf',
    storageBucket: 'placement-notifier-dcaaf.appspot.com',
    androidClientId: '723862345529-r4hl06rkm0ssps3ggbuirc8nkqjndd0u.apps.googleusercontent.com',
    iosClientId: '723862345529-cd2dpvllpbk04n2ohu91f4gqheg32bj0.apps.googleusercontent.com',
    iosBundleId: 'com.example.placementNotifier',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV8ryIVBcr1o4S3OZRPVBvrcKPzIibGiE',
    appId: '1:723862345529:ios:e6625aa51e1fb1a2163ae8',
    messagingSenderId: '723862345529',
    projectId: 'placement-notifier-dcaaf',
    storageBucket: 'placement-notifier-dcaaf.appspot.com',
    androidClientId: '723862345529-r4hl06rkm0ssps3ggbuirc8nkqjndd0u.apps.googleusercontent.com',
    iosClientId: '723862345529-emv8ac93o26mogv6nhsmrjnv13i1hvf2.apps.googleusercontent.com',
    iosBundleId: 'com.example.placementNotifier.RunnerTests',
  );
}
